import Head from 'next/head';
import DiceGame from '@/components/DiceGame/DiceGame';
import { StyledSection, SubHeading } from '@/components/styles';

export default function Dice() {
    return (
        <>
            <Head>
                <title>Text You Luck</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <StyledSection>
                <SubHeading>Can you guess the next roll?</SubHeading>
                <DiceGame />
            </StyledSection>
        </>
    );
}
