import Head from 'next/head';
import CardsGame from '@/components/CardsGame/CardsGame';
import { StyledSection, SubHeading } from '@/components/styles';

const FindPairs = () => {
    return (
        <>
            <Head>
                <title>Text You Luck</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <StyledSection>
                <SubHeading as={'h1'}>Find Pairs</SubHeading>
                <CardsGame />
            </StyledSection>
        </>
    );
};

export default FindPairs;
